# -*- coding: utf-8 -*-
"""
/***************************************************************************
 adumanis
                                 A QGIS plugin
 adumanis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-07
        copyright            : (C) 2022 by Naufal Akbar
        email                : ufalakbar111@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load adumanis class from file adumanis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .adumanis import adumanis
    return adumanis(iface)
